/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as SidebetsLiveRouteImport } from './routes/sidebets-live'
import { Route as SidebetsRouteImport } from './routes/sidebets'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users_.$userId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches_.$matchId'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebetsLiveRoute = SidebetsLiveRouteImport.update({
  id: '/sidebets-live',
  path: '/sidebets-live',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebetsRoute = SidebetsRouteImport.update({
  id: '/sidebets',
  path: '/sidebets',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches_/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/entry': typeof EntryRoute
  '/groups': typeof GroupsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leagues': typeof LeaguesRoute
  '/matches': typeof MatchesRoute
  '/rules': typeof RulesRoute
  '/sidebets': typeof SidebetsRoute
  '/sidebets-live': typeof SidebetsLiveRoute
  '/tips': typeof TipsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/entry': typeof EntryRoute
  '/groups': typeof GroupsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leagues': typeof LeaguesRoute
  '/matches': typeof MatchesRoute
  '/rules': typeof RulesRoute
  '/sidebets': typeof SidebetsRoute
  '/sidebets-live': typeof SidebetsLiveRoute
  '/tips': typeof TipsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/entry': typeof EntryRoute
  '/groups': typeof GroupsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leagues': typeof LeaguesRoute
  '/matches': typeof MatchesRoute
  '/rules': typeof RulesRoute
  '/sidebets': typeof SidebetsRoute
  '/sidebets-live': typeof SidebetsLiveRoute
  '/tips': typeof TipsRoute
  '/matches_/$matchId': typeof MatchesMatchIdRoute
  '/users_/$userId': typeof UsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/entry'
    | '/groups'
    | '/leaderboard'
    | '/leagues'
    | '/matches'
    | '/rules'
    | '/sidebets'
    | '/sidebets-live'
    | '/tips'
    | '/matches/$matchId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/entry'
    | '/groups'
    | '/leaderboard'
    | '/leagues'
    | '/matches'
    | '/rules'
    | '/sidebets'
    | '/sidebets-live'
    | '/tips'
    | '/matches/$matchId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/entry'
    | '/groups'
    | '/leaderboard'
    | '/leagues'
    | '/matches'
    | '/rules'
    | '/sidebets'
    | '/sidebets-live'
    | '/tips'
    | '/matches_/$matchId'
    | '/users_/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EntryRoute: typeof EntryRoute
  GroupsRoute: typeof GroupsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LeaguesRoute: typeof LeaguesRoute
  MatchesRoute: typeof MatchesRoute
  RulesRoute: typeof RulesRoute
  SidebetsRoute: typeof SidebetsRoute
  SidebetsLiveRoute: typeof SidebetsLiveRoute
  TipsRoute: typeof TipsRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidebets-live': {
      id: '/sidebets-live'
      path: '/sidebets-live'
      fullPath: '/sidebets-live'
      preLoaderRoute: typeof SidebetsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidebets': {
      id: '/sidebets'
      path: '/sidebets'
      fullPath: '/sidebets'
      preLoaderRoute: typeof SidebetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$userId': {
      id: '/users_/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches_/$matchId': {
      id: '/matches_/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EntryRoute: EntryRoute,
  GroupsRoute: GroupsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LeaguesRoute: LeaguesRoute,
  MatchesRoute: MatchesRoute,
  RulesRoute: RulesRoute,
  SidebetsRoute: SidebetsRoute,
  SidebetsLiveRoute: SidebetsLiveRoute,
  TipsRoute: TipsRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
